// 十二星座目录。数据驱动，后续可任意增删。
// 每颗星：x/y 为 0-100 相对坐标；数组顺序 = 点亮顺序 = 连线顺序。
// silhouette 为星座虚影（完成点亮后淡显），viewBox 0 0 100 100 的描边路径。

import { requiredEnergyFor } from './energy'

export interface ConstellationStar {
  id: string
  name: string
  nameEn: string
  mass: string // 重量（简化科普描述）
  massSolar: number // 太阳质量倍数，用于计算所需能量
  distance: string // 位置（距离描述）
  color: string // 颜色（光谱型 + 颜色）
  magnitude: string // 亮度
  recorded: string // 记录/发现时间
  story: string // 小故事
  x: number
  y: number
}

export interface Constellation {
  id: string
  name: string
  symbol: string
  intro: string // 星座介绍（完成点亮后回顾）
  silhouette: string // 虚影 SVG 内容
  stars: ConstellationStar[]
}

export const CONSTELLATIONS: Constellation[] = [
  {
    id: 'aries',
    name: '白羊座',
    symbol: '♈',
    intro:
      '白羊座源自希腊神话中长着金羊毛的公羊。它曾驮着佛里克索斯与赫勒逃离危难，最终被献祭，金羊毛成为后世英雄远征的目标。夜空中，它由两段弯曲的羊角线条构成。',
    silhouette: '<path d="M26 76 C22 58 36 44 48 32 C60 44 74 58 70 76" /><path d="M32 68 C30 54 42 46 48 40 M64 68 C66 54 54 46 48 40" />',
    stars: [
      {
        id: 'aries-1',
        name: '娄宿三',
        nameEn: 'Hamal',
        mass: '橙巨星，约 1.5 倍太阳质量',
        massSolar: 1.5,
        distance: '约 66 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 2.0，全星座最亮',
        recorded: '公元前 2 世纪喜帕恰斯星表已有记载',
        story: '白羊座最亮的星，名字源自阿拉伯语"羊头"，是整个白羊的起点。',
        x: 30,
        y: 44,
      },
      {
        id: 'aries-2',
        name: '娄宿一',
        nameEn: 'Sheratan',
        mass: '双星系统，约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 60 光年',
        color: '白色（A 型）',
        magnitude: '视星等 2.6',
        recorded: '古希腊星表有载，中国"娄宿"星官一员',
        story: '与娄宿三一起构成羊角，两千多年前的春分点曾落在它附近。',
        x: 24,
        y: 56,
      },
      {
        id: 'aries-3',
        name: '娄宿二',
        nameEn: 'Mesarthim',
        mass: '双星，约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 164 光年',
        color: '白色（A 型）',
        magnitude: '视星等 3.9',
        recorded: '1664 年胡克最早用望远镜确认的双星之一',
        story: '早期天文学的里程碑：它证明有些"一颗星"其实是两颗。',
        x: 38,
        y: 58,
      },
      {
        id: 'aries-4',
        name: '天阴四',
        nameEn: 'Botein',
        mass: 'K 型巨星，约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 168 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 4.4',
        recorded: '托勒密《天文学大成》（公元 2 世纪）有载',
        story: '名字源自阿拉伯语"小肚子"，安静地挂在羊身中段。',
        x: 50,
        y: 66,
      },
      {
        id: 'aries-5',
        name: '白羊座 ε',
        nameEn: 'ε Ari',
        mass: '双星，合计约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 290 光年',
        color: '白色（A 型）',
        magnitude: '视星等 4.6',
        recorded: '1603 年拜耳星表以希腊字母命名',
        story: '没有专属中文名的一颗，用希腊字母编号，是羊身靠后的一环。',
        x: 62,
        y: 70,
      },
      {
        id: 'aries-6',
        name: '胃宿三',
        nameEn: '41 Ari',
        mass: '蓝白色 B 型星，约 3 倍太阳质量',
        massSolar: 3,
        distance: '约 160 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 3.6',
        recorded: '以弗兰斯蒂德编号 41 记载于 1712 年星表',
        story: '落在羊尾处，是这只羊最年轻明亮的一颗。',
        x: 74,
        y: 62,
      },
    ],
  },
  {
    id: 'taurus',
    name: '金牛座',
    symbol: '♉',
    intro:
      '金牛座是宙斯化身而成的白色公牛，他把腓尼基公主欧罗巴驮过大海，成为欧洲之名的由来。夜空中，它的星群构成一个明显的 V 字牛面，两角向两侧伸出。',
    silhouette:
      '<path d="M28 52 C28 34 40 26 50 26 C60 26 72 34 72 52 C72 68 62 76 50 76 C38 76 28 68 28 52" /><path d="M36 30 C32 18 26 12 20 14 M64 30 C68 18 74 12 80 14" /><path d="M42 44 a3 3 0 1 0 0.01 0 M58 44 a3 3 0 1 0 0.01 0" />',
    stars: [
      {
        id: 'tau-1',
        name: '毕宿五',
        nameEn: 'Aldebaran',
        mass: '橙巨星，约 1.5 倍太阳质量',
        massSolar: 1.5,
        distance: '约 65 光年',
        color: '橙红色（K 型）',
        magnitude: '视星等 0.87，全天最亮星之一',
        recorded: '名字意为"追随者"，古希腊星表有载',
        story: '金牛的眼睛，紧跟在昴星团身后升起，像在追逐七姐妹。',
        x: 50,
        y: 55,
      },
      {
        id: 'tau-2',
        name: '五车五',
        nameEn: 'Elnath',
        mass: '约 4.5 倍太阳质量',
        massSolar: 4.5,
        distance: '约 134 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 1.65',
        recorded: '同时被划入金牛与御夫两个星座的边界星',
        story: '牛角尖上的星，几千年间星座边界改划，它一直站在两星座之间。',
        x: 32,
        y: 28,
      },
      {
        id: 'tau-3',
        name: '天关星',
        nameEn: 'ζ Tau',
        mass: '约 11 倍太阳质量',
        massSolar: 11,
        distance: '约 440 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 3.0',
        recorded: '中国"天关"星官：宋代曾在此附近记录超新星',
        story: '1054 年，就在它旁边爆发了著名的"天关客星"——如今的蟹状星云。',
        x: 62,
        y: 30,
      },
      {
        id: 'tau-4',
        name: '毕宿八',
        nameEn: 'λ Tau',
        mass: '约 7 倍太阳质量',
        massSolar: 7,
        distance: '约 480 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 3.4（周期性变暗）',
        recorded: '1784 年古德里克发现它是食双星',
        story: '一颗星周期性地遮住另一颗，亮度三天半一个轮回——最早的"变星"之一。',
        x: 55,
        y: 48,
      },
      {
        id: 'tau-5',
        name: '毕宿一',
        nameEn: 'ε Tau',
        mass: '约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 147 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.5',
        recorded: '2007 年发现它有一颗巨行星环绕',
        story: '牛脸 V 字的一员，身边还藏着一颗比木星更重的行星。',
        x: 42,
        y: 52,
      },
      {
        id: 'tau-6',
        name: '毕宿三',
        nameEn: 'δ Tau',
        mass: '约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 159 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.8',
        recorded: '毕宿星团成员，星团年龄约 6 亿年',
        story: '它是毕宿星团的一员——一群一起出生、一起旅行的恒星兄弟。',
        x: 58,
        y: 58,
      },
      {
        id: 'tau-7',
        name: '毕宿四',
        nameEn: 'γ Tau',
        mass: '约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 154 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.65',
        recorded: '毕宿星团成员，自古有载',
        story: 'V 字牛面的下角，和毕宿五隔着牛脸遥遥相对。',
        x: 48,
        y: 68,
      },
    ],
  },
  {
    id: 'gemini',
    name: '双子座',
    symbol: '♊',
    intro:
      '双子座是卡斯托尔与波吕克斯这对兄弟——一个凡人、一个神明，情谊之深感动宙斯，让他们共享永生、交替出现在天空。夜空中两条平行的人形线条正是兄弟二人。',
    silhouette:
      '<path d="M32 24 a5 5 0 1 0 0.01 0 M68 24 a5 5 0 1 0 0.01 0" /><path d="M32 30 L30 60 M68 30 L70 60" /><path d="M31 40 L20 48 M31 40 L42 50 M69 40 L80 48 M69 40 L58 50" /><path d="M30 60 L24 78 M30 60 L38 78 M70 60 L62 78 M70 60 L76 78" />',
    stars: [
      {
        id: 'gem-1',
        name: '北河二',
        nameEn: 'Castor',
        mass: '六合星系统，合计约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 51 光年',
        color: '白色（A 型）',
        magnitude: '视星等 1.58',
        recorded: '1678 年卡西尼发现它是双星',
        story: '看起来是一颗，其实是六颗星纠缠在一起——兄弟的象征。',
        x: 34,
        y: 30,
      },
      {
        id: 'gem-2',
        name: '北河三',
        nameEn: 'Pollux',
        mass: '橙巨星，约 1.9 倍太阳质量',
        massSolar: 1.9,
        distance: '约 34 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 1.14，双子座最亮',
        recorded: '2006 年发现它有一颗系外行星',
        story: '比兄弟北河二亮一点——因为它是那位"神"的儿子。',
        x: 40,
        y: 50,
      },
      {
        id: 'gem-3',
        name: '井宿三',
        nameEn: 'Alhena',
        mass: '约 2.8 倍太阳质量',
        massSolar: 2.8,
        distance: '约 109 光年',
        color: '白色（A 型）',
        magnitude: '视星等 1.93',
        recorded: '名字意为"骆驼颈上的烙印"，阿拉伯星表有载',
        story: '兄弟二人脚下的第三颗亮星，串起双子座的两条线。',
        x: 48,
        y: 70,
      },
      {
        id: 'gem-4',
        name: '井宿一',
        nameEn: 'μ Gem',
        mass: '红巨星，约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 230 光年',
        color: '红色（M 型）',
        magnitude: '视星等 2.9',
        recorded: '中国"井宿"星官成员，自古有载',
        story: '一颗正在衰老的红巨星，是兄弟右臂上的一抹暖色。',
        x: 58,
        y: 44,
      },
      {
        id: 'gem-5',
        name: '井宿五',
        nameEn: 'ε Gem',
        mass: '黄超巨星，约 7 倍太阳质量',
        massSolar: 7,
        distance: '约 845 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 3.06',
        recorded: '古希腊星表有载',
        story: '隔着八百多光年的遥远巨星，是兄弟伸出的那条腿。',
        x: 66,
        y: 60,
      },
      {
        id: 'gem-6',
        name: '钺',
        nameEn: 'δ Gem',
        mass: '约 1.7 倍太阳质量',
        massSolar: 1.7,
        distance: '约 60 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 3.5',
        recorded: '中国星官"钺"命名，古代兵器之意',
        story: '古中国把这片天区看作兵器架，它就是那柄钺。',
        x: 74,
        y: 75,
      },
    ],
  },
  {
    id: 'cancer',
    name: '巨蟹座',
    symbol: '♋',
    intro:
      '巨蟹座是赫拉派去干扰赫拉克勒斯的大螃蟹，被英雄一脚踩碎；赫拉怜其忠诚，将它升上天空。它的星星黯淡，是一团散落的星群。',
    silhouette:
      '<path d="M32 52 C32 66 68 66 68 52 C68 42 58 38 50 38 C42 38 32 42 32 52" /><path d="M30 46 C24 38 18 36 14 42 C18 40 24 44 22 50 M70 46 C76 38 82 36 86 42 C82 40 76 44 78 50" /><path d="M38 62 L32 74 M50 64 L50 76 M62 62 L68 74" />',
    stars: [
      {
        id: 'cnc-1',
        name: '柳宿增三',
        nameEn: 'β Cnc',
        mass: '约 1.7 倍太阳质量',
        massSolar: 1.7,
        distance: '约 290 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.5，巨蟹座最亮',
        recorded: '托勒密星表有载',
        story: '巨蟹座最亮的一颗，也被称为"巨蟹的南钳"。',
        x: 40,
        y: 38,
      },
      {
        id: 'cnc-2',
        name: '鬼宿四',
        nameEn: 'δ Cnc',
        mass: '约 1.5 倍太阳质量',
        massSolar: 1.5,
        distance: '约 131 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.94',
        recorded: '中国"鬼宿"星官成员',
        story: '与著名的蜂巢星团（M44）相邻，古人把那里看作"积尸气"。',
        x: 58,
        y: 32,
      },
      {
        id: 'cnc-3',
        name: '轩辕增廿二',
        nameEn: 'ι Cnc',
        mass: '黄超巨星，约 3.5 倍太阳质量',
        massSolar: 3.5,
        distance: '约 330 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 4.03',
        recorded: '被编入中国"轩辕"星官的远支',
        story: '虽在巨蟹座，它的中国星名却属于轩辕一组——星官与星座的错位。',
        x: 50,
        y: 50,
      },
      {
        id: 'cnc-4',
        name: '鬼宿三',
        nameEn: 'γ Cnc',
        mass: '约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 181 光年',
        color: '白色（A 型）',
        magnitude: '视星等 4.66',
        recorded: '拜耳星表命名',
        story: '螃蟹壳上的一颗白星，安静得几乎被忽略。',
        x: 60,
        y: 48,
      },
      {
        id: 'cnc-5',
        name: '柳宿增十',
        nameEn: 'α Cnc',
        mass: '约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 174 光年',
        color: '白色（A 型）',
        magnitude: '视星等 4.26',
        recorded: '曾名为"北桥"（Acubens）',
        story: '名字意为"钳子"，是螃蟹前伸的那只螯。',
        x: 52,
        y: 62,
      },
      {
        id: 'cnc-6',
        name: '轩辕增十九',
        nameEn: '55 Cnc',
        mass: '约 0.95 倍太阳质量',
        massSolar: 0.95,
        distance: '约 41 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 5.95，肉眼勉强可见',
        recorded: '1997 年发现第一颗系外行星',
        story: '和太阳很像的一颗星，身边已确认至少五颗行星——"另一个太阳系"。',
        x: 45,
        y: 72,
      },
    ],
  },
  {
    id: 'leo',
    name: '狮子座',
    symbol: '♌',
    intro:
      '狮子座是涅墨亚的巨狮，皮毛刀枪不入，赫拉克勒斯的第一项试炼就是徒手降服它。夜空中，它的镰刀形狮首与尾部三角清晰可辨。',
    silhouette:
      '<path d="M32 32 a7 7 0 1 0 0.01 0" /><path d="M28 28 C20 40 28 54 44 52" /><path d="M42 52 C56 54 66 58 76 60" /><path d="M52 56 L50 78 M60 58 L62 80" /><path d="M76 60 C82 64 84 72 80 78" />',
    stars: [
      {
        id: 'leo-1',
        name: '轩辕十四',
        nameEn: 'Regulus',
        mass: '约 3.8 倍太阳质量，高速自转',
        massSolar: 3.8,
        distance: '约 79 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 1.35',
        recorded: '古波斯四颗"王者之星"之一，喜帕恰斯星表有载',
        story: '狮子座的心脏，几乎正落在黄道上——月亮常从它身边擦过。',
        x: 30,
        y: 72,
      },
      {
        id: 'leo-2',
        name: '轩辕十三',
        nameEn: 'η Leo',
        mass: '白色超巨星，约 7 倍太阳质量',
        massSolar: 7,
        distance: '约 1300 光年',
        color: '白色（A 型）',
        magnitude: '视星等 3.5',
        recorded: '拜耳星表命名',
        story: '镰刀柄上最远的一颗，隔着千余光年与轩辕十四相望。',
        x: 32,
        y: 58,
      },
      {
        id: 'leo-3',
        name: '轩辕十二',
        nameEn: 'Algieba',
        mass: '双星，两颗巨星互相绕转，合计约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 130 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 2.0',
        recorded: '1782 年赫歇尔发现它是双星',
        story: '名字意为"狮子的鬃毛"，镰刀弧线正中的金色节点。',
        x: 44,
        y: 48,
      },
      {
        id: 'leo-4',
        name: '轩辕九',
        nameEn: 'Adhafera',
        mass: '约 2.2 倍太阳质量',
        massSolar: 2.2,
        distance: '约 274 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 3.4',
        recorded: '中国"轩辕"星官成员，自古有载',
        story: '静静待在鬃毛与镰刀之间，中国古代星官把它编入"轩辕"一组。',
        x: 46,
        y: 36,
      },
      {
        id: 'leo-5',
        name: '轩辕十',
        nameEn: 'Rasalas',
        mass: 'K 型巨星，约 1.5 倍太阳质量',
        massSolar: 1.5,
        distance: '约 124 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.9',
        recorded: '阿拉伯星表有载',
        story: '意为"狮子头北侧"，镰刀顶端的一颗。',
        x: 38,
        y: 25,
      },
      {
        id: 'leo-6',
        name: '轩辕八',
        nameEn: 'ε Leo',
        mass: '约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 247 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 2.97',
        recorded: '拜耳星表命名',
        story: '镰刀最顶端的星，划过天际的弧线到这里收住。',
        x: 29,
        y: 14,
      },
      {
        id: 'leo-7',
        name: '西上相',
        nameEn: 'Zosma',
        mass: '约 2.2 倍太阳质量',
        massSolar: 2.2,
        distance: '约 58 光年',
        color: '白色（A 型）',
        magnitude: '视星等 2.56',
        recorded: '中国"太微右垣"星官成员',
        story: '意为"腰带"，横在狮背，连起镰刀与尾部三角。',
        x: 60,
        y: 50,
      },
      {
        id: 'leo-8',
        name: '五帝座一',
        nameEn: 'Denebola',
        mass: '约 1.8 倍太阳质量',
        massSolar: 1.8,
        distance: '约 36 光年',
        color: '白色（A 型）',
        magnitude: '视星等 2.14',
        recorded: '古希腊星表有载',
        story: '意为"狮子的尾巴"，与轩辕十四、大角、角宿一组成"春季大三角"。',
        x: 76,
        y: 68,
      },
    ],
  },
  {
    id: 'virgo',
    name: '处女座',
    symbol: '♍',
    intro:
      '处女座常被看作正义与丰收的女神，手持麦穗——角宿一在拉丁语中就是"麦穗"之意。它是黄道上最大的星座，像一个斜倚的人形。',
    silhouette:
      '<path d="M50 20 a5 5 0 1 0 0.01 0" /><path d="M50 26 L50 46" /><path d="M50 34 L38 48 M50 34 L62 48" /><path d="M50 46 L36 80 L64 80 Z" />',
    stars: [
      {
        id: 'vir-1',
        name: '角宿一',
        nameEn: 'Spica',
        mass: '双星，主星约 11 倍太阳质量',
        massSolar: 11,
        distance: '约 250 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 0.98，全天最亮星之一',
        recorded: '中国"角宿"星官之首，秋分定标星',
        story: '女神手中的麦穗。两千年前，喜帕恰斯靠它发现了岁差。',
        x: 62,
        y: 72,
      },
      {
        id: 'vir-2',
        name: '东次将',
        nameEn: 'Porrima',
        mass: '双星，合计约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 38 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 2.74',
        recorded: '1718 年布拉德雷发现它是双星',
        story: '一对几乎一模一样的孪生恒星，绕一圈要 169 年。',
        x: 40,
        y: 42,
      },
      {
        id: 'vir-3',
        name: '右执法',
        nameEn: 'Zavijava',
        mass: '约 1.1 倍太阳质量',
        massSolar: 1.1,
        distance: '约 36 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 3.6',
        recorded: '太微垣"执法"星官，与太阳十分相似',
        story: '一颗和太阳很像的星，1919 年日全食曾借它验证光线弯曲。',
        x: 44,
        y: 30,
      },
      {
        id: 'vir-4',
        name: '亢宿四',
        nameEn: 'δ Vir',
        mass: '红巨星，约 1.5 倍太阳质量',
        massSolar: 1.5,
        distance: '约 198 光年',
        color: '红色（M 型）',
        magnitude: '视星等 3.38',
        recorded: '中国"亢宿"星官成员',
        story: '女神衣裙上的一颗红宝石，正在膨胀成红巨星。',
        x: 50,
        y: 58,
      },
      {
        id: 'vir-5',
        name: '角宿二',
        nameEn: 'ζ Vir',
        mass: '约 2.2 倍太阳质量',
        massSolar: 2.2,
        distance: '约 74 光年',
        color: '白色（A 型）',
        magnitude: '视星等 3.37',
        recorded: '拜耳星表命名',
        story: '与角宿一相邻，两颗"角"标定了中国古代的秋分点。',
        x: 68,
        y: 55,
      },
      {
        id: 'vir-6',
        name: '东上相',
        nameEn: 'Vindemiatrix',
        mass: '约 2.6 倍太阳质量',
        massSolar: 2.6,
        distance: '约 110 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 2.83',
        recorded: '意为"采葡萄者"，古罗马用它预报葡萄成熟',
        story: '它清晨升起时，古罗马人就知道：该收葡萄了。',
        x: 58,
        y: 38,
      },
    ],
  },
  {
    id: 'libra',
    name: '天秤座',
    symbol: '♎',
    intro:
      '天秤座是正义女神手中的天平，也是黄道十二宫中唯一以器物命名的星座。两千年前，秋分点正落在它身上，昼夜在此等长。',
    silhouette:
      '<path d="M50 22 L50 46" /><path d="M28 34 L72 34" /><path d="M30 34 L26 48 M70 34 L74 48" /><path d="M18 48 C18 58 34 58 34 48 M66 48 C66 58 82 58 82 48" />',
    stars: [
      {
        id: 'lib-1',
        name: '氐宿一',
        nameEn: 'Zubenelgenubi',
        mass: '双星，合计约 2.8 倍太阳质量',
        massSolar: 2.8,
        distance: '约 77 光年',
        color: '白色（A 型）',
        magnitude: '视星等 2.75',
        recorded: '名字意为"南边的钳子"，原属天蝎座',
        story: '曾经是天蝎的钳子，星座边界重划后归了天秤。',
        x: 38,
        y: 50,
      },
      {
        id: 'lib-2',
        name: '氐宿四',
        nameEn: 'Zubeneschamali',
        mass: '约 3.5 倍太阳质量',
        massSolar: 3.5,
        distance: '约 185 光年',
        color: '蓝白色（B 型）——传说中唯一的"绿色星"',
        magnitude: '视星等 2.61',
        recorded: '许多古代文献记载它呈现绿色',
        story: '天上几乎没有绿星，它是唯一常被古人描述为绿色的。',
        x: 44,
        y: 38,
      },
      {
        id: 'lib-3',
        name: '折威七',
        nameEn: 'σ Lib',
        mass: '红巨星，约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 288 光年',
        color: '红色（M 型）',
        magnitude: '视星等 3.29',
        recorded: '拜耳星表命名',
        story: '天平横梁右端的一颗红星，和左端的蓝白形成对比。',
        x: 58,
        y: 40,
      },
      {
        id: 'lib-4',
        name: '氐宿三',
        nameEn: 'γ Lib',
        mass: '约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 163 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.91',
        recorded: '中国"氐宿"星官成员',
        story: '秤盘下方的一颗，稳稳压住天平的右半。',
        x: 62,
        y: 54,
      },
      {
        id: 'lib-5',
        name: '折威五',
        nameEn: 'υ Lib',
        mass: '约 1.2 倍太阳质量',
        massSolar: 1.2,
        distance: '约 195 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.6',
        recorded: '弗兰斯蒂德星表编号',
        story: '天平支柱下的一颗，离我们不算远也不算近。',
        x: 52,
        y: 66,
      },
    ],
  },
  {
    id: 'scorpius',
    name: '天蝎座',
    symbol: '♏',
    intro:
      '天蝎座是毒杀猎人俄里翁的蝎子，宙斯把两者分置于天空两端，永不相见。它的星群弯成一条清晰的蝎尾，心宿二就是那颗红色的蝎心。',
    silhouette:
      '<path d="M46 28 C36 24 28 24 22 30 M22 30 C28 28 34 32 32 36 M46 28 C52 22 60 24 62 32" /><path d="M46 28 C56 34 62 44 58 56" /><path d="M58 56 C64 60 70 62 70 70 C70 78 62 82 56 78" /><path d="M52 40 L44 52 M56 46 L62 58 M54 52 L46 64" />',
    stars: [
      {
        id: 'sco-1',
        name: '房宿四',
        nameEn: 'Acrab',
        mass: '多合星系统',
        massSolar: 6,
        distance: '约 530 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 2.6',
        recorded: '托勒密星表有载',
        story: '蝎子的头部，由至少四颗星纠缠而成。',
        x: 32,
        y: 18,
      },
      {
        id: 'sco-2',
        name: '房宿三',
        nameEn: 'Dschubba',
        mass: '约 12 倍太阳质量',
        massSolar: 12,
        distance: '约 400 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 2.3',
        recorded: '2000 年曾突然增亮，至今原因不明',
        story: '意为"前额"，两千年前曾突然变亮，如今已恢复平静。',
        x: 40,
        y: 28,
      },
      {
        id: 'sco-3',
        name: '心宿二',
        nameEn: 'Antares',
        mass: '红超巨星，约 15 倍太阳质量',
        massSolar: 15,
        distance: '约 550 光年',
        color: '红色（M 型）',
        magnitude: '视星等 1.06',
        recorded: '中国商代即称"大火"，用来定农时',
        story: '天蝎之心，体积是太阳的几亿倍。名字意为"火星的对手"——因为它和火星一样红。',
        x: 50,
        y: 42,
      },
      {
        id: 'sco-4',
        name: '尾宿一',
        nameEn: 'Al Niyat',
        mass: '约 12 倍太阳质量',
        massSolar: 12,
        distance: '约 735 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 2.9',
        recorded: '阿拉伯星表有载',
        story: '意为"动脉"，紧贴在心宿二身旁，是心脏外的一圈光晕。',
        x: 58,
        y: 52,
      },
      {
        id: 'sco-5',
        name: '尾宿二',
        nameEn: 'Larawag',
        mass: '约 1.2 倍太阳质量',
        massSolar: 1.2,
        distance: '约 64 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 2.3',
        recorded: '2017 年才被国际天文学联合会正式定名',
        story: '尾巴的开端，2017 年才被正式定名，是全天较近的亮星之一。',
        x: 64,
        y: 62,
      },
      {
        id: 'sco-6',
        name: '尾宿五',
        nameEn: 'Sargas',
        mass: '约 3 倍太阳质量',
        massSolar: 3,
        distance: '约 270 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 1.86',
        recorded: '古代两河流域星表有载',
        story: '蝎尾弯曲处的支点，夏季南天最亮的几颗星之一。',
        x: 72,
        y: 70,
      },
      {
        id: 'sco-7',
        name: '尾宿八',
        nameEn: 'Shaula',
        mass: '约 10 倍太阳质量',
        massSolar: 10,
        distance: '约 570 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 1.62',
        recorded: '名字意为"翘起的尾巴"',
        story: '就是蝎子毒刺上的锋芒。',
        x: 62,
        y: 82,
      },
      {
        id: 'sco-8',
        name: '尾宿九',
        nameEn: 'Lesath',
        mass: '约 11 倍太阳质量',
        massSolar: 11,
        distance: '约 580 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 2.7',
        recorded: '与尾宿八并称"猫眼"',
        story: '毒刺旁的一颗，夜里看像一对发亮的小眼睛。',
        x: 52,
        y: 88,
      },
    ],
  },
  {
    id: 'sagittarius',
    name: '射手座',
    symbol: '♐',
    intro:
      '射手座常被描绘为贤者喀戎——半人马族的智者，张弓搭箭指向天蝎之心。夜空中它的主星组成一把"茶壶"，是夏季银河最热闹的天区。',
    silhouette:
      '<path d="M32 72 L66 38" /><path d="M66 38 L58 34 M66 38 L62 48" /><path d="M32 72 L24 68 M32 72 L28 80" /><path d="M40 26 C54 16 68 16 76 24" />',
    stars: [
      {
        id: 'sgr-1',
        name: '箕宿三',
        nameEn: 'Kaus Australis',
        mass: '约 3.5 倍太阳质量',
        massSolar: 3.5,
        distance: '约 143 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 1.85，射手座最亮',
        recorded: '意为"南边的弓"',
        story: '茶壶的"壶底"，也是整张弓最南端的支点。',
        x: 36,
        y: 42,
      },
      {
        id: 'sgr-2',
        name: '斗宿四',
        nameEn: 'Nunki',
        mass: '约 7.8 倍太阳质量',
        massSolar: 7.8,
        distance: '约 228 光年',
        color: '蓝白色（B 型）',
        magnitude: '视星等 2.05',
        recorded: '巴比伦星表中最古老的恒星名之一',
        story: '名字来自四千年前的巴比伦语，是茶壶的"壶盖"。',
        x: 48,
        y: 50,
      },
      {
        id: 'sgr-3',
        name: '斗宿六',
        nameEn: 'Ascella',
        mass: '约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 88 光年',
        color: '白色（A 型）',
        magnitude: '视星等 2.6',
        recorded: '意为"腋下"，罗马时代有载',
        story: '茶壶的"壶嘴"，银河正从那里倾泻而出。',
        x: 60,
        y: 54,
      },
      {
        id: 'sgr-4',
        name: '箕宿一',
        nameEn: 'γ Sgr',
        mass: '约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 96 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 2.98',
        recorded: '中国"箕宿"星官成员',
        story: '弓的上缘，和箕宿三一起张开了射手座的弓。',
        x: 30,
        y: 56,
      },
      {
        id: 'sgr-5',
        name: '斗宿二',
        nameEn: 'Kaus Borealis',
        mass: '约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 78 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 2.82',
        recorded: '意为"北边的弓"',
        story: '茶壶的"壶顶"，与箕宿三、斗宿六构成壶身三角。',
        x: 42,
        y: 34,
      },
      {
        id: 'sgr-6',
        name: '箕宿四',
        nameEn: 'η Sgr',
        mass: '红巨星，约 1.5 倍太阳质量',
        massSolar: 1.5,
        distance: '约 149 光年',
        color: '红色（M 型）',
        magnitude: '视星等 3.1',
        recorded: '中国"箕宿"星官成员',
        story: '弓弦上的一颗红星，像一支搭在弦上的箭镞。',
        x: 54,
        y: 66,
      },
    ],
  },
  {
    id: 'capricornus',
    name: '摩羯座',
    symbol: '♑',
    intro:
      '摩羯座是半羊半鱼的牧神潘。他躲避怪物时跃入水中，情急之下变形，上半身是羊、下半身是鱼，从此定格在天空。',
    silhouette:
      '<path d="M34 26 C28 14 38 8 46 16" /><path d="M42 20 C50 18 54 24 54 30" /><path d="M42 28 C44 44 54 52 64 56" /><path d="M64 56 C76 54 82 62 78 72 C72 80 60 78 58 68" />',
    stars: [
      {
        id: 'cap-1',
        name: '垒壁阵四',
        nameEn: 'Deneb Algedi',
        mass: '食双星，合计约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 39 光年',
        color: '白色（A 型）',
        magnitude: '视星等 2.85，摩羯座最亮',
        recorded: '1784 年古德里克发现它亮度周期性变化',
        story: '名字意为"山羊的尾巴"，是半羊半鱼的身体分界处。',
        x: 58,
        y: 62,
      },
      {
        id: 'cap-2',
        name: '牛宿一',
        nameEn: 'Dabih',
        mass: '多合星系统，约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 328 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.05',
        recorded: '意为"屠夫"，阿拉伯星表有载',
        story: '摩羯的额头，古阿拉伯人把它看作祭牲之额。',
        x: 55,
        y: 48,
      },
      {
        id: 'cap-3',
        name: '牛宿二',
        nameEn: 'Algedi',
        mass: '双星，约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 106 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 3.58',
        recorded: '意为"小山羊"，肉眼可见的"光学双星"',
        story: '两颗本不相干的星在视线方向上重叠，看起来像一对羊角。',
        x: 45,
        y: 42,
      },
      {
        id: 'cap-4',
        name: '牛宿四',
        nameEn: 'ω Cap',
        mass: '红巨星，约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 630 光年',
        color: '红色（M 型）',
        magnitude: '视星等 4.12',
        recorded: '中国"牛宿"星官成员',
        story: '羊身与鱼尾之间的一抹暗红。',
        x: 66,
        y: 70,
      },
      {
        id: 'cap-5',
        name: '牛宿六',
        nameEn: 'ψ Cap',
        mass: '约 1.3 倍太阳质量',
        massSolar: 1.3,
        distance: '约 48 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 4.14',
        recorded: '弗兰斯蒂德星表编号',
        story: '鱼尾末端的一颗，离我们不到五十光年。',
        x: 70,
        y: 60,
      },
      {
        id: 'cap-6',
        name: '垒壁阵三',
        nameEn: 'Nashira',
        mass: '约 2 倍太阳质量',
        massSolar: 2,
        distance: '约 139 光年',
        color: '白色（A 型）',
        magnitude: '视星等 3.67',
        recorded: '意为"带来好消息者"',
        story: '名字像一句祝福：带来好消息的人。',
        x: 48,
        y: 66,
      },
    ],
  },
  {
    id: 'aquarius',
    name: '水瓶座',
    symbol: '♒',
    intro:
      '水瓶座是特洛伊王子伽倪墨得斯，因俊美被宙斯带上奥林匹斯，为众神斟酒。夜空中，他倾倒的水瓶化作了蜿蜒的水流。',
    silhouette:
      '<path d="M38 20 L50 20 L50 32 L38 32 Z M38 32 L34 36 M50 32 L54 36" /><path d="M22 42 C32 32 42 52 52 42 C62 32 72 52 82 42" /><path d="M26 58 C36 48 46 68 56 58 C66 48 76 68 86 58" />',
    stars: [
      {
        id: 'aqr-1',
        name: '危宿一',
        nameEn: 'Sadalsuud',
        mass: '黄超巨星，约 6 倍太阳质量',
        massSolar: 6,
        distance: '约 540 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 2.9，水瓶座最亮',
        recorded: '意为"幸运中的最幸运者"',
        story: '和太阳同类型的超巨星，是水瓶倾倒出的第一束光。',
        x: 52,
        y: 28,
      },
      {
        id: 'aqr-2',
        name: '虚宿一',
        nameEn: 'Sadalmelik',
        mass: '黄超巨星，约 6.5 倍太阳质量',
        massSolar: 6.5,
        distance: '约 520 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 2.95',
        recorded: '意为"国王的幸运星"，中国"虚宿"星官',
        story: '水瓶的右肩，古中国把它看作"虚"——冬季夜空的标志。',
        x: 44,
        y: 38,
      },
      {
        id: 'aqr-3',
        name: '坟墓二',
        nameEn: 'ζ Aqr',
        mass: '双星，约 1.8 倍太阳质量',
        massSolar: 1.8,
        distance: '约 92 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 3.65',
        recorded: '名字源于阿拉伯语的误译，"幸运"变成了"坟墓"',
        story: '一个美丽的翻译事故：本是"幸运"，误译成了"坟墓"。',
        x: 60,
        y: 40,
      },
      {
        id: 'aqr-4',
        name: '危宿三',
        nameEn: 'Albali',
        mass: '约 2.2 倍太阳质量',
        massSolar: 2.2,
        distance: '约 215 光年',
        color: '白色（A 型）',
        magnitude: '视星等 3.78',
        recorded: '意为"吞咽者"，水瓶倾斜的瓶口',
        story: '瓶口边的一颗，水流正是从它身边倾泻而下。',
        x: 66,
        y: 58,
      },
      {
        id: 'aqr-5',
        name: '羽林军廿六',
        nameEn: 'Skat',
        mass: '约 2.5 倍太阳质量',
        massSolar: 2.5,
        distance: '约 160 光年',
        color: '白色（A 型）',
        magnitude: '视星等 3.27',
        recorded: '意为"腿"，中国"羽林军"星官成员',
        story: '水瓶的腿，踩在南方低空的水流里。',
        x: 58,
        y: 62,
      },
      {
        id: 'aqr-6',
        name: '危宿二',
        nameEn: 'Sadachbia',
        mass: '约 2.7 倍太阳质量',
        massSolar: 2.7,
        distance: '约 158 光年',
        color: '白色（A 型）',
        magnitude: '视星等 3.86',
        recorded: '意为"帐篷里的幸运星"',
        story: '水流中段的星，像帐篷里透出的光。',
        x: 50,
        y: 52,
      },
    ],
  },
  {
    id: 'pisces',
    name: '双鱼座',
    symbol: '♓',
    intro:
      '双鱼座是爱与美之神阿佛洛狄忒和她的儿子厄洛斯。为躲避怪物，母子化为两条鱼，用一根丝带相连，从此再不分离。',
    silhouette:
      '<path d="M50 52 a4 4 0 1 0 0.01 0" /><path d="M50 48 C40 40 32 34 26 34 M50 56 C60 64 68 70 74 70" /><path d="M22 28 C16 34 18 44 26 44 C34 44 34 34 30 28 C28 25 24 25 22 28" /><path d="M24 30 L18 24 M24 30 L18 34" /><path d="M78 76 C84 70 82 60 74 60 C66 60 66 70 70 76 C72 79 76 79 78 76" /><path d="M76 74 L82 80 M76 74 L82 68" />',
    stars: [
      {
        id: 'psc-1',
        name: '右更二',
        nameEn: 'η Psc',
        mass: '约 3 倍太阳质量',
        massSolar: 3,
        distance: '约 350 光年',
        color: '黄色（G 型）',
        magnitude: '视星等 3.62，双鱼座最亮',
        recorded: '中国"右更"星官成员',
        story: '双鱼座最亮的一颗，站在东边那条鱼的鱼尾上。',
        x: 60,
        y: 58,
      },
      {
        id: 'psc-2',
        name: '外屏七',
        nameEn: 'γ Psc',
        mass: '约 2.2 倍太阳质量',
        massSolar: 2.2,
        distance: '约 138 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 3.7',
        recorded: '中国"外屏"星官成员',
        story: '西边那条鱼的身体，泛着温和的橙光。',
        x: 50,
        y: 66,
      },
      {
        id: 'psc-3',
        name: '霹雳一',
        nameEn: 'ι Psc',
        mass: '约 1.3 倍太阳质量',
        massSolar: 1.3,
        distance: '约 45 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 4.13',
        recorded: '中国"霹雳"星官成员',
        story: '西边那条鱼的鱼尾，离我们不到五十光年。',
        x: 42,
        y: 44,
      },
      {
        id: 'psc-4',
        name: '外屏增一',
        nameEn: 'θ Psc',
        mass: '约 1.7 倍太阳质量',
        massSolar: 1.7,
        distance: '约 159 光年',
        color: '橙色（K 型）',
        magnitude: '视星等 4.27',
        recorded: '中国"外屏"星官增星',
        story: '游在丝带上方的一颗，是这条鱼的背鳍。',
        x: 50,
        y: 36,
      },
      {
        id: 'psc-5',
        name: '奎宿十六',
        nameEn: 'ω Psc',
        mass: '约 1.5 倍太阳质量',
        massSolar: 1.5,
        distance: '约 106 光年',
        color: '黄白色（F 型）',
        magnitude: '视星等 4.01',
        recorded: '中国"奎宿"星官成员',
        story: '西边那条鱼的腹部，贴着黄道游动。',
        x: 36,
        y: 46,
      },
      {
        id: 'psc-6',
        name: '外屏三',
        nameEn: 'Alrescha',
        mass: '双星，约 1.9 倍太阳质量',
        massSolar: 1.9,
        distance: '约 151 光年',
        color: '白色（A 型）',
        magnitude: '视星等 3.82',
        recorded: '意为"绳子"——两条鱼之间的结',
        story: '双鱼之结：丝带在这里打结，把两条鱼永远连在一起。',
        x: 48,
        y: 50,
      },
    ],
  },
]

export function getConstellation(id: string): Constellation | undefined {
  return CONSTELLATIONS.find((c) => c.id === id)
}

export function findConstellationStar(constellationId: string, starId: string): ConstellationStar | null {
  const c = getConstellation(constellationId)
  return c?.stars.find((s) => s.id === starId) ?? null
}

export interface StarEnergy {
  energy: number
  required: number
}

export interface ConstellationProgress {
  lit: number // 完全点亮
  partial: number // 点亮中（弦月态）
  total: number
  remaining: number // 还差多少能量
  next: ConstellationStar | null // 下一颗要点的星（形状顺序第一颗未满的）
  complete: boolean
}

export function progressOf(c: Constellation, energies: ReadonlyMap<string, StarEnergy>): ConstellationProgress {
  let lit = 0
  let partial = 0
  let remaining = 0
  let next: ConstellationStar | null = null
  for (const s of c.stars) {
    const e = energies.get(s.id)
    if (!e) {
      remaining += requiredEnergyFor(s.massSolar)
      if (!next) next = s
      continue
    }
    if (e.energy >= e.required) lit++
    else {
      partial++
      remaining += e.required - e.energy
      if (!next) next = s
    }
  }
  return { lit, partial, total: c.stars.length, remaining, next, complete: next === null }
}
